---
- name: DEmo of webserver configuration
  hosts: servera
  tasks:
   - name: Synchronize file
     ansible.builtin.fetch:
      src: /tmp/test
      dest: /tmp/prefix-{{ inventory_hostname }}
      flat: yes

