---
- hosts: servera
  tasks:
   -  yum: name=httpd state=present
   -  service: name=httpd state=started enabled=yes
   -  shell: echo hello > /var/www/html/index.html
   #-  firewalld: service=http permanent=yes immediate=true state=enabled
        

                

...
