---
- name: DEmo of webserver configuration
  hosts: servera
  tasks:
      - name: Install package
        yum:
         name: httpd
         state: present
      - name: Deliver the content
        copy: 
         content: HelloWorld
         dest: /var/www/html/index.html
        notify: 
         - myhandler1
      - name: OPen firewall port   
        firewalld:
         service: http
         immediate: yes
         permanent: yes
         state: enabled
  handlers:
      - name: myhandler1
        service:
         name: httpd
         state: started
         enabled: yes
        
...
