---
- name: Demo of import Playbook
  hosts: servera
  tasks: 
    - name: From main playbook
      ansible.builtin.debug: msg="I am from MAIN FILE"
    - name: import task1
      import_tasks: tasks/task1.yml
    - name: import task2
      import_tasks: tasks/task2.yml
...
