---
- name: Demo of import Playbook
  hosts: servera
  tasks: 
    - name: From main playbook
      debug: msg="I am from MAIN FILE"
- name: import playbook1
  include: import/play1.yml

- name: import playbook2
  include: import/play2.yml
...
